name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Run Linter
        run: npm run lint
      - name: Run Prettier
        run: npm run prettier
      - name: Run Typechecker
        run: npm run typecheck
